### ISSUE TITLE
HaNi NeReDe Bu BoTuN "PreMiD" rPc'sİ hE? GiDiP SaDeCe BoTu YaPtIn DeMi ÇaQaL SeNi?!?!?

### ISSUE THREAD

**Issue by thisisnithy** [eggsywashere/Epey-Bot#1]
Acilen gidip PreMiD Store'da Epey RPC'si görmek istiyoruz yoksa bu bot Murkish Heçkt Tim tarafından yarın elinden alınacaktır...

**Comment by eggsywashere** [comment]
thank you. fixed**:))**
